version: '3.8'
services:
  graphql:
    build:
      context: ./graphql
    ports:
      - 8080:8080
    volumes:
      - ./graphql:/app
  bandcamp-scraper:
    build:
      context: .
      dockerfile: ./bandcamp-user-data/Dockerfile.dev
    ports:
      - 8081:8080
    volumes:
      - ./bandcamp-user-data:/app
