steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']
    dir: 'functions/graphql'
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['build', '--outDir', '/build-dir/dist']
    dir: 'functions/graphql'
    volumes:
      - name: 'build-dir'
        path: '/build-dir'
  - name: 'bash'
    args: ['cp', 'package.json', '/build-dir/dist']
    volumes:
      - name: 'build-dir'
        path: '/build-dir'
  - name: 'gcr.io/cloud-builders/gcloud'
    volumes:
      - name: 'build-dir'
        path: '/build-dir'
    args:
      - functions
      - deploy
      - graphql
      - --runtime=nodejs12
      # Exported function name
      - --entry-point=handler
      - --source=/build-dir/dist
      - --trigger-http
      - --allow-unauthenticated
